### PR TITLE
marvin final proj idea

### PR DESCRIPTION
**Pull request by MarvinPerry**
On a scale of 1 to 5, how would you rate your comfort level with the material in this assignment?

What, if anything, did you find challenging about this assignment?

What, if anything, did you find easy about this assignment?

### CODE REVIEW

**Comment by ZakkMan** [comment]
Hey Marvin, I get an error when I try to visit your final project repository. Is it set to private?

Thanks,
Zakk

**Comment by MarvinPerry** [comment]
@ZakkMan You should be able to access it now.

**Comment by ZakkMan** [comment]
@MarvinPerry looks good! Here is the assignment that was due today for reference: https://github.com/ga-students/js-dc-4/blob/master/16-spas/assignment.md

Just make sure you provide these things.

Thanks!
Zakk

**Comment by MarvinPerry** [comment]
@ZakkMan I just realized that you probably couldn't/didn't see that I actually did that part when it was due last week because it was also private. Can you see this? https://github.com/ga-students/live-gallery

**Comment by ZakkMan** [comment]
@MarvinPerry - I see that and it looks great! What I'm looking for is your UI draft (either a list or images) and your technical requirements.

See the assignment here which details the requirements for those: https://github.com/ga-students/js-dc-4/blob/master/16-spas/assignment.md

See a sample here: https://github.com/ga-students/js-dc-4/blob/master/final-project/sample-readme.md

Let me know if you have any questions!

**Comment by MarvinPerry** [comment]
@ZakkMan I saw this right before I left to head here. Writing it up now.

**Pull request closed without merging**
