### PR TITLE
updated post class expectations

### PR DESCRIPTION
**Pull request by josephofiowa**
update class 19+ readme

### CODE REVIEW

**Comment by josephofiowa** [comment]
@christinelovett No merge? Mean

**Comment by christinelovett** [comment]
You'll get there one day. #neverstoplearning

**Comment by christinelovett** [comment]
But really this was an accident. I will merge bc friendship.

**Comment by josephofiowa** [comment]
screen shot 2017-03-28 at 6 42 19 pm

Nice

**Comment by christinelovett** [comment]
baller

**Pull request merged**
