### PR TITLE
templatingHW try

### PR DESCRIPTION
**Pull request by fbohz**
On a scale of 1 to 5, how would you rate your comfort level with the material in this assignment?
2

What, if anything, did you find challenging about this assignment?
Understanding handlebars. I had troubles adding the new string. 

What, if anything, did you find easy about this assignment?

### CODE REVIEW

**Comment by fbohz** [comment]
I added my ideas for the project too. Please let me know any feedback. Thanks!

**Comment by christinelovett** [comment]
Hey Felipe, which file is your project idea in?

**Comment by fbohz** [comment]
Is under the final project folder ('final-project')

**Comment by fbohz** [comment]
### Potential Project Ideas by Felipe Bohorquez

##### Idea 1 - Food Truck App
Food truck aggregator and follower by twitter feed and geolocate on map. Food truck gets added by inputing twiter handle. 

##### Idea 2 - Short-Films Feed
Provide daily short films by connecting to youtube on most played ones. Shortfilms can be added also by url. Shortfilms can be rated by clicking on stars.

++++
-Flix
	Make a wheel that you can rotate based upon short film genre.
	When you rotate the wheel it will spit a short film you can watch based upon genre.
	It will use Youtube API to spit out short-films based on genres
	After you watch you can share and like/unlike.

**Comment by christinelovett** [comment]
Project feedback in bold above :-)

**Comment by fbohz** [comment]
I'm just back from travel so was able to see your comment. Thanks Christine! Probably I'll go with the short film one. I'll take a look at the visualization tools.

**Pull request closed without merging**
